In [1]:
import requests
from bs4 import BeautifulSoup  
import pandas as pd
import xlrd

In [2]:
urlbase = 'https://www.pro-football-reference.com/teams/'
injuries = '_injuries.htm'

In [3]:
#create team base url's for webscraper to run through
arizona = 'crd/2011'
atlanta = 'atl/2011'
buffalo = 'buf/2011'
baltimore = 'rav/2011'
carolina = 'car/2011'
cincinnati = 'cin/2011'
cleveland = 'cle/2011'
chicago = 'chi/2011'
dallas = 'dal/2011'
denver = 'den/2011'
detroit = 'det/2011'
greenbay = 'gnb/2011'
houston = 'htx/2011'
indy = 'clt/2011'
kc = 'kan/2011'
lac = 'sdg/2011'
lar = 'ram/2011'
jacksonville = 'jax/2011'
miami = 'mia/2011'
minnesota = 'min/2011'
newengland = 'new/2011'
neworleans = 'nor/2011'
nyg = 'nyg/2011'
nyj = 'nyj/2011'
oakland = 'rai/2011'
philly = 'rai/2011'
sanfran = 'sfo/2011'
seattle = 'sea/2011'
pittsburgh = 'pit/2011'
tampabay = 'tam/2011'
tennessee = 'oti/2011'
washington = 'was/2011'

In [4]:
<table class="sortable stats_table now_sortable sticky_table re1 le1" id="team_injuries" data-cols-to-freeze="1">

SyntaxError: invalid syntax (<ipython-input-4-fb800ae83ad2>, line 1)

In [ ]:
def injury(url, pages):
    final_list = []
    df = pd.DataFrame()
    for p in range(1, pages + 1): # pages + 1 because range stops at the last number
        response = requests.post(url + (p) + injuries) # Goes to URL and adds p to end of it to select page.
        soup = BeautifulSoup(response.content, 'html')
        tables = soup.find_all('table', attrs = {'class': "sortable stats_table now_sortable sticky_table re1 le1"})
        result_list = pd.read_html(str(tables[0]))
        final_list = result_list[0]
        df = df.append(final_list, ignore_index = True)
    return df

In [10]:
#import the injury data excel notebook and individual sheets as their own df's
arizona_df = pd.ExcelFile('../data/arizona.xlsx')
arizona_df1 = pd.read_excel(arizona_df, '2011')
arizona_df2 = pd.read_excel(arizona_df, '2012')
arizona_df3 = pd.read_excel(arizona_df, '2013')
arizona_df4 = pd.read_excel(arizona_df, '2014')
arizona_df5 = pd.read_excel(arizona_df, '2015')
arizona_df6 = pd.read_excel(arizona_df, '2016')
arizona_df7 = pd.read_excel(arizona_df, '2017')
arizona_df8 = pd.read_excel(arizona_df, '2018')
arizona_df9 = pd.read_excel(arizona_df, '2019')
arizona_df10 = pd.read_excel(arizona_df, '2020')

atlanta_df = pd.ExcelFile('../data/atlanta.xlsx')
atlanta_df1 = pd.read_excel(atlanta_df, '2011')
atlanta_df2 = pd.read_excel(atlanta_df, '2012')
atlanta_df3 = pd.read_excel(atlanta_df, '2013')
atlanta_df4 = pd.read_excel(atlanta_df, '2014')
atlanta_df5 = pd.read_excel(atlanta_df, '2015')
atlanta_df6 = pd.read_excel(atlanta_df, '2016')
atlanta_df7 = pd.read_excel(atlanta_df, '2017')
atlanta_df8 = pd.read_excel(atlanta_df, '2018')
atlanta_df9 = pd.read_excel(atlanta_df, '2019')
atlanta_df10 = pd.read_excel(atlanta_df, '2020')

baltimore_df = pd.ExcelFile('../data/baltimore.xlsx')
baltimore_df1 = pd.read_excel(baltimore_df, '2011')
baltimore_df2 = pd.read_excel(baltimore_df, '2012')
baltimore_df3 = pd.read_excel(baltimore_df, '2013')
baltimore_df4 = pd.read_excel(baltimore_df, '2014')
baltimore_df5 = pd.read_excel(baltimore_df, '2015')
baltimore_df6 = pd.read_excel(baltimore_df, '2016')
baltimore_df7 = pd.read_excel(baltimore_df, '2017')
baltimore_df8 = pd.read_excel(baltimore_df, '2018')
baltimore_df9 = pd.read_excel(baltimore_df, '2019')
baltimore_df10 = pd.read_excel(baltimore_df, '2020')

buffalo_df = pd.ExcelFile('../data/baltimore.xlsx')
buffalo_df1 = pd.read_excel(buffalo_df, '2011')
buffalo_df2 = pd.read_excel(buffalo_df, '2012')
buffalo_df3 = pd.read_excel(buffalo_df, '2013')
buffalo_df4 = pd.read_excel(buffalo_df, '2014')
buffalo_df5 = pd.read_excel(buffalo_df, '2015')
buffalo_df6 = pd.read_excel(buffalo_df, '2016')
buffalo_df7 = pd.read_excel(buffalo_df, '2017')
buffalo_df8 = pd.read_excel(buffalo_df, '2018')
buffalo_df9 = pd.read_excel(buffalo_df, '2019')
buffalo_df10 = pd.read_excel(buffalo_df, '2020')

carolina_df = pd.ExcelFile('../data/carolina.xlsx')
carolina_df1 = pd.read_excel(carolina_df, '2011')
carolina_df2 = pd.read_excel(carolina_df, '2012')
caroina_df3 = pd.read_excel(carolina_df, '2013')
carolina_df4 = pd.read_excel(carolina_df, '2014')
carolina_df5 = pd.read_excel(carolina_df, '2015')
carolina_df6 = pd.read_excel(carolina_df, '2016')
carolina_df7 = pd.read_excel(carolina_df, '2017')
carolina_df8 = pd.read_excel(carolina_df, '2018')
carolina_df9 = pd.read_excel(carolina_df, '2019')
carolina_df10 = pd.read_excel(carolina_df, '2020')

chargers_df = pd.ExcelFile('../data/chargers.xlsx')
chargers_df1 = pd.read_excel(chargers_df, '2011')
chargers_df2 = pd.read_excel(chargers_df, '2012')
chargers_df3 = pd.read_excel(chargers_df, '2013')
chargers_df4 = pd.read_excel(chargers_df, '2014')
chargers_df5 = pd.read_excel(chargers_df, '2015')
chargers_df6 = pd.read_excel(chargers_df, '2016')
chargers_df7 = pd.read_excel(chargers_df, '2017')
chargers_df8 = pd.read_excel(chargers_df, '2018')
chargers_df9 = pd.read_excel(chargers_df, '2019')
chargers_df10 = pd.read_excel(chargers_df, '2020')

chicago_df = pd.ExcelFile('../data/chicago.xlsx')
chicago_df1 = pd.read_excel(chicago_df, '2011')
chicago_df2 = pd.read_excel(chicago_df, '2012')
chicago_df3 = pd.read_excel(chicago_df, '2013')
chicago_df4 = pd.read_excel(chicago_df, '2014')
chicago_df5 = pd.read_excel(chicago_df, '2015')
chicago_df6 = pd.read_excel(chicago_df, '2016')
chicago_df7 = pd.read_excel(chicago_df, '2017')
chicago_df8 = pd.read_excel(chicago_df, '2018')
chicago_df9 = pd.read_excel(chicago_df, '2019')
chicago_df10 = pd.read_excel(chicago_df, '2020')

cincinatti_df = pd.ExcelFile('../data/cincinatti.xlsx')
cincinatti_df1 = pd.read_excel(cincinatti_df, '2011')
cincinatti_df2 = pd.read_excel(cincinatti_df, '2012')
cincinatti_df3 = pd.read_excel(cincinatti_df, '2013')
cincinatti_df4 = pd.read_excel(cincinatti_df, '2014')
cincinatti_df5 = pd.read_excel(cincinatti_df, '2015')
cincinatti_df6 = pd.read_excel(cincinatti_df, '2016')
cincinatti_df7 = pd.read_excel(cincinatti_df, '2017')
cincinatti_df8 = pd.read_excel(cincinatti_df, '2018')
cincinatti_df9 = pd.read_excel(cincinatti_df, '2019')
cincinatti_df10 = pd.read_excel(cincinatti_df, '2020')

cleveland_df = pd.ExcelFile('../data/cleveland.xlsx')
cleveland_df1 = pd.read_excel(cleveland_df, '2011')
cleveland_df2 = pd.read_excel(cleveland_df, '2012')
cleveland_df3 = pd.read_excel(cleveland_df, '2013')
cleveland_df4 = pd.read_excel(cleveland_df, '2014')
cleveland_df5 = pd.read_excel(cleveland_df, '2015')
cleveland_df6 = pd.read_excel(cleveland_df, '2016')
cleveland_df7 = pd.read_excel(cleveland_df, '2017')
cleveland_df8 = pd.read_excel(cleveland_df, '2018')
cleveland_df9 = pd.read_excel(cleveland_df, '2019')
cleveland_df10 = pd.read_excel(cleveland_df, '2020')

dallas_df = pd.ExcelFile('../data/dallas.xlsx')
dallas_df1 = pd.read_excel(dallas_df, '2011')
dallas_df2 = pd.read_excel(dallas_df, '2012')
dallas_df3 = pd.read_excel(dallas_df, '2013')
dallas_df4 = pd.read_excel(dallas_df, '2014')
dallas_df5 = pd.read_excel(dallas_df, '2015')
dallas_df6 = pd.read_excel(dallas_df, '2016')
dallas_df7 = pd.read_excel(dallas_df, '2017')
dallas_df8 = pd.read_excel(dallas_df, '2018')
dallas_df9 = pd.read_excel(dallas_df, '2019')
dallas_df10 = pd.read_excel(dallas_df, '2020')

denver = pd.ExcelFile('../data/denver.xlsx')
denver1 = pd.read_excel(denver, '2011')
denver2 = pd.read_excel(denver, '2012')
denver3 = pd.read_excel(denver, '2013')
denver4 = pd.read_excel(denver, '2014')
denver5 = pd.read_excel(denver, '2015')
denver6 = pd.read_excel(denver, '2016')
denver7 = pd.read_excel(denver, '2017')
denver8 = pd.read_excel(denver, '2018')
denver9 = pd.read_excel(denver, '2019')
denver10 = pd.read_excel(denver, '2020')

detroit = pd.ExcelFile('../data/detroit.xlsx')
detroit1 = pd.read_excel(detroit, '2011')
detroit2 = pd.read_excel(detroit, '2012')
detroit3 = pd.read_excel(detroit, '2013')
detroit4 = pd.read_excel(detroit, '2014')
detroit5 = pd.read_excel(detroit, '2015')
detroit6 = pd.read_excel(detroit, '2016')
detroit7 = pd.read_excel(detroit, '2017')
detroit8 = pd.read_excel(detroit, '2018')
detroit9 = pd.read_excel(detroit, '2019')
detroit10 = pd.read_excel(detroit, '2020')

greenbay = pd.ExcelFile('../data/greenbay.xlsx')
greenbay1 = pd.read_excel(greenbay, '2011')
greenbay2 = pd.read_excel(greenbay, '2012')
greenbay3 = pd.read_excel(greenbay, '2013')
greenbay4 = pd.read_excel(greenbay, '2014')
greenbay5 = pd.read_excel(greenbay, '2015')
greenbay6 = pd.read_excel(greenbay, '2016')
greenbay7 = pd.read_excel(greenbay, '2017')
greenbay8 = pd.read_excel(greenbay, '2018')
greenbay9 = pd.read_excel(greenbay, '2019')
greenbay10 = pd.read_excel(greenbay, '2020')

houston = pd.ExcelFile('../data/houston.xlsx')
houston1 = pd.read_excel(houston, '2011')
houston2 = pd.read_excel(houston, '2012')
houston3 = pd.read_excel(houston, '2013')
houston4 = pd.read_excel(houston, '2014')
houston5 = pd.read_excel(houston, '2015')
houston6 = pd.read_excel(houston, '2016')
houston7 = pd.read_excel(houston, '2017')
houston8 = pd.read_excel(houston, '2018')
houston9 = pd.read_excel(houston, '2019')
houston10 = pd.read_excel(houston, '2020')

indy = pd.ExcelFile('../data/indy.xlsx')
indy1 = pd.read_excel(indy, '2011')
indy2 = pd.read_excel(indy, '2012')
indy3 = pd.read_excel(indy, '2013')
indy4 = pd.read_excel(indy, '2014')
indy5 = pd.read_excel(indy, '2015')
indy6 = pd.read_excel(indy, '2016')
indy7 = pd.read_excel(indy, '2017')
indy8 = pd.read_excel(indy, '2018')
indy9 = pd.read_excel(indy, '2019')
indy10 = pd.read_excel(indy, '2020')

jacksonville = pd.ExcelFile('../data/jacksonville.xlsx')
jacksonville1 = pd.read_excel(jacksonville, '2011')
jacksonville2 = pd.read_excel(jacksonville, '2012')
jacksonville3 = pd.read_excel(jacksonville, '2013')
jacksonville4 = pd.read_excel(jacksonville, '2014')
jacksonville5 = pd.read_excel(jacksonville, '2015')
jacksonville6 = pd.read_excel(jacksonville, '2016')
jacksonville7 = pd.read_excel(jacksonville, '2017')
jacksonville8 = pd.read_excel(jacksonville, '2018')
jacksonville9 = pd.read_excel(jacksonville, '2019')
jacksonville10 = pd.read_excel(jacksonville, '2020')

kansascity = pd.ExcelFile('../data/kansascity.xlsx')
kansascity1 = pd.read_excel(kansascity, '2011')
kansascity2 = pd.read_excel(kansascity, '2012')
kansascity3 = pd.read_excel(kansascity, '2013')
kansascity4 = pd.read_excel(kansascity, '2014')
kansascity5 = pd.read_excel(kansascity, '2015')
kansascity6 = pd.read_excel(kansascity, '2016')
kansascity7 = pd.read_excel(kansascity, '2017')
kansascity8 = pd.read_excel(kansascity, '2018')
kansascity9 = pd.read_excel(kansascity, '2019')
kansascity10 = pd.read_excel(kansascity, '2020')

miami = pd.ExcelFile('../data/miami.xlsx')
miami1 = pd.read_excel(miami, '2011')
miami2 = pd.read_excel(miami, '2012')
miami3 = pd.read_excel(miami, '2013')
miami4 = pd.read_excel(miami, '2014')
miami5 = pd.read_excel(miami, '2015')
miami6 = pd.read_excel(miami, '2016')
miami7 = pd.read_excel(miami, '2017')
miami8 = pd.read_excel(miami, '2018')
miami9 = pd.read_excel(miami, '2019')
miami10 = pd.read_excel(miami, '2020')

minnesota = pd.ExcelFile('../data/minnesota.xlsx')
minnesota1 = pd.read_excel(minnesota, '2011')
minnesota2 = pd.read_excel(minnesota, '2012')
minnesota3 = pd.read_excel(minnesota, '2013')
minnesota4 = pd.read_excel(minnesota, '2014')
minnesota5 = pd.read_excel(minnesota, '2015')
minnesota6 = pd.read_excel(minnesota, '2016')
minnesota7 = pd.read_excel(minnesota, '2017')
minnesota8 = pd.read_excel(minnesota, '2018')
minnesota9 = pd.read_excel(minnesota, '2019')
minnesota10 = pd.read_excel(minnesota, '2020')

newengland = pd.ExcelFile('../data/newengland.xlsx')
newengland1 = pd.read_excel(newengland, '2011')
newengland2 = pd.read_excel(newengland, '2012')
newengland3 = pd.read_excel(newengland, '2013')
newengland4 = pd.read_excel(newengland, '2014')
newengland5 = pd.read_excel(newengland, '2015')
newengland6 = pd.read_excel(newengland, '2016')
newengland7 = pd.read_excel(newengland, '2017')
newengland8 = pd.read_excel(newengland, '2018')
newengland9 = pd.read_excel(newengland, '2019')
newengland10 = pd.read_excel(newengland, '2020')

neworleans = pd.ExcelFile('../data/neworleans.xlsx')
neworleans1 = pd.read_excel(neworleans, '2011')
neworleans2 = pd.read_excel(neworleans, '2012')
neworleans3 = pd.read_excel(neworleans, '2013')
neworleans4 = pd.read_excel(neworleans, '2014')
neworleans5 = pd.read_excel(neworleans, '2015')
neworleans6 = pd.read_excel(neworleans, '2016')
neworleans7 = pd.read_excel(neworleans, '2017')
neworleans8 = pd.read_excel(neworleans, '2018')
neworleans9 = pd.read_excel(neworleans, '2019')
neworleans10 = pd.read_excel(neworleans, '2020')

nyg = pd.ExcelFile('../data/nyg.xlsx')
nyg1 = pd.read_excel(nyg, '2011')
nyg2 = pd.read_excel(nyg, '2012')
nyg3 = pd.read_excel(nyg, '2013')
nyg4 = pd.read_excel(nyg, '2014')
nyg5 = pd.read_excel(nyg, '2015')
nyg6 = pd.read_excel(nyg, '2016')
nyg7 = pd.read_excel(nyg, '2017')
nyg8 = pd.read_excel(nyg, '2018')
nyg9 = pd.read_excel(nyg, '2019')
nyg10 = pd.read_excel(nyg, '2020')

nyj = pd.ExcelFile('../data/nyj.xlsx')
nyj1 = pd.read_excel(nyj, '2011')
nyj2 = pd.read_excel(nyj, '2012')
nyj3 = pd.read_excel(nyj, '2013')
nyj4 = pd.read_excel(nyj, '2014')
nyj5 = pd.read_excel(nyj, '2015')
nyj6 = pd.read_excel(nyj, '2016')
nyj7 = pd.read_excel(nyj, '2017')
nyj8 = pd.read_excel(nyj, '2018')
nyj9 = pd.read_excel(nyj, '2019')
nyj10 = pd.read_excel(nyj, '2020')

oakland = pd.ExcelFile('../data/oakland.xlsx')
oakland1 = pd.read_excel(oakland, '2011')
oakland2 = pd.read_excel(oakland, '2012')
oakland3 = pd.read_excel(oakland, '2013')
oakland4 = pd.read_excel(oakland, '2014')
oakland5 = pd.read_excel(oakland, '2015')
oakland6 = pd.read_excel(oakland, '2016')
oakland7 = pd.read_excel(oakland, '2017')
oakland8 = pd.read_excel(oakland, '2018')
oakland9 = pd.read_excel(oakland, '2019')
oakland10 = pd.read_excel(oakland, '2020')

oakland = pd.ExcelFile('../data/oakland.xlsx')
oakland1 = pd.read_excel(oakland, '2011')
oakland2 = pd.read_excel(oakland, '2012')
oakland3 = pd.read_excel(oakland, '2013')
oakland4 = pd.read_excel(oakland, '2014')
oakland5 = pd.read_excel(oakland, '2015')
oakland6 = pd.read_excel(oakland, '2016')
oakland7 = pd.read_excel(oakland, '2017')
oakland8 = pd.read_excel(oakland, '2018')
oakland9 = pd.read_excel(oakland, '2019')
oakland10 = pd.read_excel(oakland, '2020')

philadelphia = pd.ExcelFile('../data/philadelphia.xlsx')
philadelphia1 = pd.read_excel(philadelphia, '2011')
philadelphia2 = pd.read_excel(philadelphia, '2012')
philadelphia3 = pd.read_excel(philadelphia, '2013')
philadelphia4 = pd.read_excel(philadelphia, '2014')
philadelphia5 = pd.read_excel(philadelphia, '2015')
philadelphia6 = pd.read_excel(philadelphia, '2016')
philadelphia7 = pd.read_excel(philadelphia, '2017')
philadelphia8 = pd.read_excel(philadelphia, '2018')
philadelphia9 = pd.read_excel(philadelphia, '2019')
philadelphia10 = pd.read_excel(philadelphia, '2020')

pittsburgh = pd.ExcelFile('../data/pittsburgh.xlsx')
pittsburgh1 = pd.read_excel(pittsburgh, '2011')
pittsburgh2 = pd.read_excel(pittsburgh, '2012')
pittsburgh3 = pd.read_excel(pittsburgh, '2013')
pittsburgh4 = pd.read_excel(pittsburgh, '2014')
pittsburgh5 = pd.read_excel(pittsburgh, '2015')
pittsburgh6 = pd.read_excel(pittsburgh, '2016')
pittsburgh7 = pd.read_excel(pittsburgh, '2017')
pittsburgh8 = pd.read_excel(pittsburgh, '2018')
pittsburgh9 = pd.read_excel(pittsburgh, '2019')
pittsburgh10 = pd.read_excel(pittsburgh, '2020')

rams = pd.ExcelFile('../data/rams.xlsx')
rams1 = pd.read_excel(rams, '2011')
rams2 = pd.read_excel(rams, '2012')
rams3 = pd.read_excel(rams, '2013')
rams4 = pd.read_excel(rams, '2014')
rams5 = pd.read_excel(rams, '2015')
rams6 = pd.read_excel(rams, '2016')
rams7 = pd.read_excel(rams, '2017')
rams8 = pd.read_excel(rams, '2018')
rams9 = pd.read_excel(rams, '2019')
rams10 = pd.read_excel(rams, '2020')

redskins = pd.ExcelFile('../data/redskins.xlsx')
redskins1 = pd.read_excel(redskins, '2011')
redskins2 = pd.read_excel(redskins, '2012')
redskins3 = pd.read_excel(redskins, '2013')
redskins4 = pd.read_excel(redskins, '2014')
redskins5 = pd.read_excel(redskins, '2015')
redskins6 = pd.read_excel(redskins, '2016')
redskins7 = pd.read_excel(redskins, '2017')
redskins8 = pd.read_excel(redskins, '2018')
redskins9 = pd.read_excel(redskins, '2019')
redskins10 = pd.read_excel(redskins, '2020')

sanfran = pd.ExcelFile('../data/sanfran.xlsx')
sanfran1 = pd.read_excel(sanfran, '2011')
sanfran2 = pd.read_excel(sanfran, '2012')
sanfran3 = pd.read_excel(sanfran, '2013')
sanfran4 = pd.read_excel(sanfran, '2014')
sanfran5 = pd.read_excel(sanfran, '2015')
sanfran6 = pd.read_excel(sanfran, '2016')
sanfran7 = pd.read_excel(sanfran, '2017')
sanfran8 = pd.read_excel(sanfran, '2018')
sanfran9 = pd.read_excel(sanfran, '2019')
sanfran10 = pd.read_excel(sanfran, '2020')

seattle = pd.ExcelFile('../data/seattle.xlsx')
seattle1 = pd.read_excel(seattle, '2011')
seattle2 = pd.read_excel(seattle, '2012')
seattle3 = pd.read_excel(seattle, '2013')
seattle4 = pd.read_excel(seattle, '2014')
seattle5 = pd.read_excel(seattle, '2015')
seattle6 = pd.read_excel(seattle, '2016')
seattle7 = pd.read_excel(seattle, '2017')
seattle8 = pd.read_excel(seattle, '2018')
seattle9 = pd.read_excel(seattle, '2019')
seattle10 = pd.read_excel(seattle, '2020')

tampabay = pd.ExcelFile('../data/tampabay.xlsx')
tampabay1 = pd.read_excel(tampabay, '2011')
tampabay2 = pd.read_excel(tampabay, '2012')
tampabay3 = pd.read_excel(tampabay, '2013')
tampabay4 = pd.read_excel(tampabay, '2014')
tampabay5 = pd.read_excel(tampabay, '2015')
tampabay6 = pd.read_excel(tampabay, '2016')
tampabay7 = pd.read_excel(tampabay, '2017')
tampabay8 = pd.read_excel(tampabay, '2018')
tampabay9 = pd.read_excel(tampabay, '2019')
tampabay10 = pd.read_excel(tampabay, '2020')

tennessee = pd.ExcelFile('../data/tennessee.xlsx')
tennessee1 = pd.read_excel(tennessee, '2011')
tennessee2 = pd.read_excel(tennessee, '2012')
tennessee3 = pd.read_excel(tennessee, '2013')
tennessee4 = pd.read_excel(tennessee, '2014')
tennessee5 = pd.read_excel(tennessee, '2015')
tennessee6 = pd.read_excel(tennessee, '2016')
tennessee7 = pd.read_excel(tennessee, '2017')
tennessee8 = pd.read_excel(tennessee, '2018')
tennessee9 = pd.read_excel(tennessee, '2019')
tennessee10 = pd.read_excel(tennessee, '2020')

washington = pd.ExcelFile('../data/washington.xlsx')
washington5 = pd.read_excel(washington, '2015')
washington6 = pd.read_excel(washington, '2016')
washington7 = pd.read_excel(washington, '2017')
washington8 = pd.read_excel(washington, '2018')
washington9 = pd.read_excel(washington, '2019')
washington10 = pd.read_excel(washington, '2020')

In [17]:
washington10.head()

,Player,09/13vs. PHI,09/20vs. ARI,09/27vs. CLE,10/04vs. BAL,10/11vs. LAR,10/18vs. NYG,10/25vs. DAL,11/08vs. NYG,11/15vs. DET,11/22vs. CIN,11/26vs. DAL,12/07vs. PIT,12/13vs. SFO,12/20vs. SEA
0,Kyle Allen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,IR,IR,IR,IR,IR
1,Ryan Anderson,NaN,NaN,NaN,Q,NaN,Q,NaN,NaN,NaN,O,O,NaN,IR,IR
2,Jeff Badet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q,NaN,NaN,NaN,NaN,NaN
3,Marcus Baugh,NaN,NaN,NaN,NaN,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Ryan Bee,IR,IR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
#Import the player position and salary notebooks
ari = pd.ExcelFile('../data/ari.xlsx')
ari1 = pd.read_excel(ari, '2015')
ari2 = pd.read_excel(ari, '2016')
ari3 = pd.read_excel(ari, '2017')
ari4 = pd.read_excel(ari, '2018')
ari5 = pd.read_excel(ari, '2019')
ari6 = pd.read_excel(ari, '2020')

atl = pd.ExcelFile('../data/atl.xlsx')
atl1 = pd.read_excel(atl, '2015')
atl2 = pd.read_excel(atl, '2016')
atl3 = pd.read_excel(atl, '2017')
atl4 = pd.read_excel(atl, '2018')
atl5 = pd.read_excel(atl, '2019')
atl6 = pd.read_excel(atl, '2020')


bal = pd.ExcelFile('../data/bal.xlsx')
bal1 = pd.read_excel(bal, '2015')
bal2 = pd.read_excel(bal, '2016')
bal3 = pd.read_excel(bal, '2017')
bal4 = pd.read_excel(bal, '2018')
bal5 = pd.read_excel(bal, '2019')
bal6 = pd.read_excel(bal, '2020')

buf = pd.ExcelFile('../data/buf.xlsx')
buf1 = pd.read_excel(buf, '2015')
buf2 = pd.read_excel(buf, '2016')
buf3 = pd.read_excel(buf, '2017')
buf4 = pd.read_excel(buf, '2018')
buf5 = pd.read_excel(buf, '2019')
buf6 = pd.read_excel(buf, '2020')

car = pd.ExcelFile('../data/car.xlsx')
car1 = pd.read_excel(car, '2015')
car2 = pd.read_excel(car, '2016')
car3 = pd.read_excel(car, '2017')
car4 = pd.read_excel(car, '2018')
car5 = pd.read_excel(car, '2019')
car6 = pd.read_excel(car, '2020')

sdg = pd.ExcelFile('../data/sdg.xlsx')
sdg1 = pd.read_excel(sdg, '2015')
sdg2 = pd.read_excel(sdg, '2016')
sdg3 = pd.read_excel(sdg, '2017')
sdg4 = pd.read_excel(sdg, '2018')
sdg5 = pd.read_excel(sdg, '2019')
sdg6 = pd.read_excel(sdg, '2020')

chi = pd.ExcelFile('../data/chi.xlsx')
chi1 = pd.read_excel(chi, '2015')
chi2 = pd.read_excel(chi, '2016')
chi3 = pd.read_excel(chi, '2017')
chi4 = pd.read_excel(chi, '2018')
chi5 = pd.read_excel(chi, '2019')
chi6 = pd.read_excel(chi, '2020')

cle = pd.ExcelFile('../data/cle.xlsx')
cle1 = pd.read_excel(cle, '2015')
cle2 = pd.read_excel(cle, '2016')
cle3 = pd.read_excel(cle, '2017')
cle4 = pd.read_excel(cle, '2018')
cle5 = pd.read_excel(cle, '2019')
cle6 = pd.read_excel(cle, '2020')

clt = pd.ExcelFile('../data/clt.xlsx')
clt1 = pd.read_excel(clt, '2015')
clt2 = pd.read_excel(clt, '2016')
clt3 = pd.read_excel(clt, '2017')
clt4 = pd.read_excel(clt, '2018')
clt5 = pd.read_excel(clt, '2019')
clt6 = pd.read_excel(clt, '2020')

dal = pd.ExcelFile('../data/dal.xlsx')
dal1 = pd.read_excel(dal, '2015')
dal2 = pd.read_excel(dal, '2016')
dal3 = pd.read_excel(dal, '2017')
dal4 = pd.read_excel(dal, '2018')
dal5 = pd.read_excel(dal, '2019')
dal6 = pd.read_excel(dal, '2020')

det = pd.ExcelFile('../data/det.xlsx')
det1 = pd.read_excel(det, '2015')
det2 = pd.read_excel(det, '2016')
det3 = pd.read_excel(det, '2017')
det4 = pd.read_excel(det, '2018')
det5 = pd.read_excel(det, '2019')
det6 = pd.read_excel(det, '2020')

gnb = pd.ExcelFile('../data/gnb.xlsx')
gnb1 = pd.read_excel(gnb, '2015')
gnb2 = pd.read_excel(gnb, '2016')
gnb3 = pd.read_excel(gnb, '2017')
gnb4 = pd.read_excel(gnb, '2018')
gnb5 = pd.read_excel(gnb, '2019')
gnb6 = pd.read_excel(gnb, '2020')

htx = pd.ExcelFile('../data/htx.xlsx')
htx1 = pd.read_excel(htx, '2015')
htx2 = pd.read_excel(htx, '2016')
htx3 = pd.read_excel(htx, '2017')
htx4 = pd.read_excel(htx, '2018')
htx5 = pd.read_excel(htx, '2019')
htx6 = pd.read_excel(htx, '2020')


jax = pd.ExcelFile('../data/jax.xlsx')
jax1 = pd.read_excel(jax, '2015')
jax2 = pd.read_excel(jax, '2016')
jax3 = pd.read_excel(jax, '2017')
jax4 = pd.read_excel(jax, '2018')
jax5 = pd.read_excel(jax, '2019')
jax6 = pd.read_excel(jax, '2020')


kan = pd.ExcelFile('../data/kan.xlsx')
kan1 = pd.read_excel(kan, '2015')
kan2 = pd.read_excel(kan, '2016')
kan3 = pd.read_excel(kan, '2017')
kan4 = pd.read_excel(kan, '2018')
kan5 = pd.read_excel(kan, '2019')
kan6 = pd.read_excel(kan, '2020')

mia = pd.ExcelFile('../data/mia.xlsx')
mia1 = pd.read_excel(mia, '2015')
mia2 = pd.read_excel(mia, '2016')
mia3 = pd.read_excel(mia, '2017')
mia4 = pd.read_excel(mia, '2018')
mia5 = pd.read_excel(mia, '2019')
mia6 = pd.read_excel(mia, '2020')

minn = pd.ExcelFile('../data/minn.xlsx')
minn1 = pd.read_excel(minn, '2015')
minn2 = pd.read_excel(minn, '2016')
minn3 = pd.read_excel(minn, '2017')
minn4 = pd.read_excel(minn, '2018')
minn5 = pd.read_excel(minn, '2019')
minn6 = pd.read_excel(minn, '2020')

new = pd.ExcelFile('../data/new.xlsx')
new1 = pd.read_excel(new, '2015')
new2 = pd.read_excel(new, '2016')
new3 = pd.read_excel(new, '2017')
new4 = pd.read_excel(new, '2018')
new5 = pd.read_excel(new, '2019')
new6 = pd.read_excel(new, '2020')

nyj_positions = pd.ExcelFile('../data/nyj_positions.xlsx')
nyj_positions1 = pd.read_excel(nyj_positions, '2015')
nyj_positions2 = pd.read_excel(nyj_positions, '2016')
nyj_positions3 = pd.read_excel(nyj_positions, '2017')
nyj_positions4 = pd.read_excel(nyj_positions, '2018')
nyj_positions5 = pd.read_excel(nyj_positions, '2019')
nyj_positions6 = pd.read_excel(nyj_positions, '2020')

pit = pd.ExcelFile('../data/pit.xlsx')
pit1 = pd.read_excel(pit, '2015')
pit2 = pd.read_excel(pit, '2016')
pit3 = pd.read_excel(pit, '2017')
pit4 = pd.read_excel(pit, '2018')
pit5 = pd.read_excel(pit, '2019')
pit6 = pd.read_excel(pit, '2020')

rai = pd.ExcelFile('../data/rai.xlsx')
rai1 = pd.read_excel(rai, '2015')
rai2 = pd.read_excel(rai, '2016')
rai3 = pd.read_excel(rai, '2017')
rai4 = pd.read_excel(rai, '2018')
rai5 = pd.read_excel(rai, '2019')
rai6 = pd.read_excel(rai, '2020')

ram = pd.ExcelFile('../data/ram.xlsx')
ram1 = pd.read_excel(ram, '2015')
ram2 = pd.read_excel(ram, '2016')
ram3 = pd.read_excel(ram, '2017')
ram4 = pd.read_excel(ram, '2018')
ram5 = pd.read_excel(ram, '2019')
ram6 = pd.read_excel(ram, '2020')

sdg = pd.ExcelFile('../data/sdg.xlsx')
sdg1 = pd.read_excel(sdg, '2015')
sdg2 = pd.read_excel(sdg, '2016')
sdg3 = pd.read_excel(sdg, '2017')
sdg4 = pd.read_excel(sdg, '2018')
sdg5 = pd.read_excel(sdg, '2019')
sdg6 = pd.read_excel(sdg, '2020')

sea = pd.ExcelFile('../data/sea.xlsx')
sea1 = pd.read_excel(sea, '2015')
sea2 = pd.read_excel(sea, '2016')
sea3 = pd.read_excel(sea, '2017')
sea4 = pd.read_excel(sea, '2018')
sea5 = pd.read_excel(sea, '2019')
sea6 = pd.read_excel(sea, '2020')

sfo = pd.ExcelFile('../data/sfo.xlsx')
sfo1 = pd.read_excel(sfo, '2015')
sfo2 = pd.read_excel(sfo, '2016')
sfo3 = pd.read_excel(sfo, '2017')
sfo4 = pd.read_excel(sfo, '2018')
sfo5 = pd.read_excel(sfo, '2019')
sfo6 = pd.read_excel(sfo, '2020')

tam = pd.ExcelFile('../data/tam.xlsx')
tam1 = pd.read_excel(tam, '2015')
tam2 = pd.read_excel(tam, '2016')
tam3 = pd.read_excel(tam, '2017')
tam4 = pd.read_excel(tam, '2018')
tam5 = pd.read_excel(tam, '2019')
tam6 = pd.read_excel(tam, '2020')

ten = pd.ExcelFile('../data/ten.xlsx')
ten1 = pd.read_excel(ten, '2015')
ten2 = pd.read_excel(ten, '2016')
ten3 = pd.read_excel(ten, '2017')
ten4 = pd.read_excel(ten, '2018')
ten5 = pd.read_excel(ten, '2019')
ten6 = pd.read_excel(ten, '2020')

was = pd.ExcelFile('../data/was.xlsx')
was1 = pd.read_excel(was, '2015')
was2 = pd.read_excel(was, '2016')
was3 = pd.read_excel(was, '2017')
was4 = pd.read_excel(was, '2018')
was5 = pd.read_excel(was, '2019')
was6 = pd.read_excel(was, '2020')

In [98]:
was3.head()

,No.,Player,Age,Pos,G,GS,Wt,Ht,College/Univ,BirthDate,Yrs,AV,Drafted (tm/rnd/yr),Salary
0,8,Kirk Cousins,29,QB,16,16,202,2020-06-03,Michigan St.,1988-08-19,5,12,Washington Redskins / 4th / 102nd pick / 2012,23943600
1,32,Samaje Perine,22,RB,16,8,240,2020-05-11,Oklahoma,1995-09-16,Rook,5,Washington Redskins / 4th / 114th pick / 2017,465000
2,20,Robert Kelley,25,rb,7,7,229,2000-06-01,Tulane,1992-10-03,1,1,NaN,540000
3,14,Ryan Grant,27,wr,16,7,195,2000-06-01,Tulane,1990-12-19,3,4,Washington Redskins / 5th / 142nd pick / 2014,690000
4,18,Josh Doctson,25,WR,16,14,205,2020-06-02,"TCU,Wyoming",1992-12-03,1,4,Washington Redskins / 1st / 22nd pick / 2016,906802

In [ ]:
tennessee4 = tennessee4.rename(columns={"09/07vs. KAN": "week_1", "09/14vs. DAL": "week 2", "09/21vs. CIN":"week 3", "09/28vs. IND":"week 4", "10/05vs. CLE" : "week 5", "10/12vs. JAX" : "week 6", "10/19vs. WAS" : "week 7", "10/26vs. HOU" : "week 8", "11/09vs. BAL" : "week 9", "11/17vs. PIT" : "week 10", "11/23vs. PHI" : "week 11", "11/30vs. HOU" : "week 12", "12/07vs. NYG" : "week 13", "12/14vs. NYJ" : "week 14", "12/18vs. JAX" : "week 15", "12/28vs. IND" : "week 16"})
tennessee4

In [101]:
rams7.head()

,Player,09/10vs. IND,09/17vs. WAS,09/21vs. SFO,10/01vs. DAL,10/08vs. SEA,10/15vs. JAX,10/22vs. ARI,11/05vs. NYG,11/12vs. HOU,11/19vs. MIN,11/26vs. NOR,12/03vs. ARI,12/10vs. PHI,12/17vs. SEA,12/24vs. TEN,12/31vs. SFO,01/06vs. ATL
0,Maurice Alexander,NaN,NaN,NaN,NaN,IR,IR,IR,IR,IR,IR,IR,IR,IR,IR,IR,IR,IR
1,Brandon Allen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IR,IR,IR,IR
2,Mark Barron,NaN,NaN,NaN,NaN,NaN,Q,Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D,NaN
3,Connor Barwin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O,Q,NaN,NaN,NaN,NaN
4,Jamon Brown,NaN,NaN,NaN,NaN,Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [105]:
#experimenting with merges 
cardinals_2015 = pd.merge(arizona_df5, ari1,how = 'inner')
                               
cardinals_2015.head(10)
#successfully merges on Player column

,Player,09/13vs. NOR,09/20vs. CHI,09/27vs. SFO,10/04vs. STL,10/11vs. DET,10/18vs. PIT,10/26vs. BAL,11/01vs. CLE,11/15vs. SEA,...,G,GS,Wt,Ht,College/Univ,BirthDate,Yrs,AV,Drafted (tm/rnd/yr),Salary
0,John Brown,NaN,NaN,NaN,P,NaN,P,Q,Q,Q,...,15,11,178,2020-05-11,Pittsburg St.,1990-04-03,1,10,Arizona Cardinals / 3rd / 91st pick / 2014,657725.0
1,Deone Bucannon,NaN,Q,P,NaN,NaN,NaN,NaN,P,NaN,...,16,16,211,2020-06-01,Washington St.,1992-08-30,1,15,Arizona Cardinals / 1st / 27th pick / 2014,1752091.0
2,Jonathan Cooper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14,9,308,2020-06-02,North Carolina,1990-01-19,2,5,Arizona Cardinals / 1st / 7th pick / 2013,3967910.0
3,Darren Fells,NaN,NaN,NaN,NaN,Q,P,O,O,P,...,14,12,270,2020-06-07,UC Irvine,1986-04-22,2,3,NaN,510000.0
4,Michael Floyd,Q,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,6,220,2020-06-03,Notre Dame,1989-11-27,3,8,Arizona Cardinals / 1st / 13th pick / 2012,3172750.0
5,Markus Golden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,6,260,2020-06-03,Missouri,1991-03-13,Rook,4,Arizona Cardinals / 2nd / 58th pick / 2015,712424.0
6,Jermaine Gresham,Q,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,12,260,2020-06-05,Oklahoma,1988-06-16,5,2,Cincinnati Bengals / 1st / 21st pick / 2010,3109375.0
7,Tony Jefferson,NaN,Q,P,NaN,NaN,P,NaN,NaN,NaN,...,16,7,211,2020-05-11,Oklahoma,1992-01-27,2,3,NaN,NaN
8,Chris Johnson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,9,195,2020-05-11,East Carolina,1985-09-23,7,6,Tennessee Titans / 1st / 24th pick / 2008,585000.0
9,David Johnson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16,5,224,2020-06-01,Northern Iowa,1991-12-16,Rook,9,Arizona Cardinals / 3rd / 86th pick / 2015,594843.0

In [109]:
cardinals_2015

,Player,09/13vs. NOR,09/20vs. CHI,09/27vs. SFO,10/04vs. STL,10/11vs. DET,10/18vs. PIT,10/26vs. BAL,11/01vs. CLE,11/15vs. SEA,...,G,GS,Wt,Ht,College/Univ,BirthDate,Yrs,AV,Drafted (tm/rnd/yr),Salary
0,John Brown,NaN,NaN,NaN,P,NaN,P,Q,Q,Q,...,15,11,178,2020-05-11,Pittsburg St.,1990-04-03,1,10,Arizona Cardinals / 3rd / 91st pick / 2014,657725.0
1,Deone Bucannon,NaN,Q,P,NaN,NaN,NaN,NaN,P,NaN,...,16,16,211,2020-06-01,Washington St.,1992-08-30,1,15,Arizona Cardinals / 1st / 27th pick / 2014,1752091.0
2,Jonathan Cooper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14,9,308,2020-06-02,North Carolina,1990-01-19,2,5,Arizona Cardinals / 1st / 7th pick / 2013,3967910.0
3,Darren Fells,NaN,NaN,NaN,NaN,Q,P,O,O,P,...,14,12,270,2020-06-07,UC Irvine,1986-04-22,2,3,NaN,510000.0
4,Michael Floyd,Q,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,6,220,2020-06-03,Notre Dame,1989-11-27,3,8,Arizona Cardinals / 1st / 13th pick / 2012,3172750.0
5,Markus Golden,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,6,260,2020-06-03,Missouri,1991-03-13,Rook,4,Arizona Cardinals / 2nd / 58th pick / 2015,712424.0
6,Jermaine Gresham,Q,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15,12,260,2020-06-05,Oklahoma,1988-06-16,5,2,Cincinnati Bengals / 1st / 21st pick / 2010,3109375.0
7,Tony Jefferson,NaN,Q,P,NaN,NaN,P,NaN,NaN,NaN,...,16,7,211,2020-05-11,Oklahoma,1992-01-27,2,3,NaN,NaN
8,Chris Johnson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,9,195,2020-05-11,East Carolina,1985-09-23,7,6,Tennessee Titans / 1st / 24th pick / 2008,585000.0
9,David Johnson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16,5,224,2020-06-01,Northern Iowa,1991-12-16,Rook,9,Arizona Cardinals / 3rd / 86th pick / 2015,594843.0
10,Rashad Johnson,NaN,NaN,NaN,NaN,P,Q,NaN,NaN,NaN,...,14,14,195,2000-06-01,Alabama,1986-01-02,6,5,Arizona Cardinals / 3rd / 95th pick / 2009,2233334.0
11,Alex Okafor,NaN,NaN,P,P,NaN,O,O,O,P,...,13,13,261,2020-06-04,Texas,1991-02-08,2,6,Arizona Cardinals / 4th / 103rd pick / 2013,703607.0
12,Jerraud Powers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q,P,...,13,13,190,2020-05-09,Auburn,1987-07-19,6,4,Indianapolis Colts / 3rd / 92nd pick / 2009,5350000.0
13,Frostee Rucker,NaN,NaN,NaN,NaN,P,NaN,P,P,NaN,...,13,13,261,2020-06-03,USC,1983-09-14,8,6,Cincinnati Bengals / 3rd / 91st pick / 2006,2181875.0
14,Lyle Sendlein,NaN,NaN,NaN,NaN,NaN,NaN,NaN,P,Q,...,15,15,299,2020-06-03,Texas,1984-03-16,8,8,NaN,2000000.0
15,Jared Veldheer,NaN,NaN,NaN,NaN,NaN,P,NaN,NaN,NaN,...,16,16,321,2020-06-08,Hillsdale,1987-06-14,5,11,Oakland Raiders / 3rd / 69th pick / 2010,8500000.0
16,LaMarr Woodley,NaN,NaN,P,P,P,Q,P,NaN,NaN,...,10,7,266,2020-06-02,Michigan,1984-11-03,8,3,Pittsburgh Steelers / 2nd / 46th pick / 2007,665000.0

In [106]:
cardinals_2015.shape

(17, 32)

In [107]:
arizona_df5.shape

(46, 19)

In [108]:
ari1.shape

(28, 14)

In [112]:
cardinals_2015.to_csv('../data/cardinals2015.csv', index = False)

In [115]:
saints_2020 =  pd.merge(neworleans10, nor6,how = 'inner')
                               
saints_2020

,Player,09/13vs. TAM,09/21vs. LVR,09/27vs. GNB,10/04vs. DET,10/12vs. LAC,10/25vs. CAR,11/01vs. CHI,11/08vs. TAM,11/15vs. SFO,...,G,GS,Wt,Ht,College/Univ,BirthDate,Yrs,AV,Drafted (tm/rnd/yr),Salary
0,Terron Armstead,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.0,11.0,304.0,2020-06-05,Ark-Pine Bluff,1991-07-23,7,NaN,New Orleans Saints / 3rd / 75th pick / 2013,1050000.0
1,Drew Brees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaT,NaN,NaT,NaN,NaN,NaN,23650000.0
2,Jared Cook,NaN,NaN,NaN,O,Q,NaN,NaN,NaN,NaN,...,12.0,4.0,254.0,2020-06-05,South Carolina,1987-04-07,11,NaN,Tennessee Titans / 3rd / 89th pick / 2009,7000000.0
3,Ken Crawley,NaN,NaN,NaN,NaN,NaN,C19,C19,NaN,NaN,...,4.0,0.0,180.0,2020-06-01,Colorado,1993-02-08,4,NaN,NaN,695882.0
4,Marcus Davenport,O,O,Q,O,Q,NaN,NaN,NaN,NaN,...,8.0,0.0,265.0,2020-06-06,Texas-San Antonio,1996-09-04,2,NaN,New Orleans Saints / 1st / 14th pick / 2018,1729263.0
5,Nick Easton,NaN,NaN,NaN,NaN,NaN,O,O,NaN,NaN,...,11.0,8.0,303.0,2020-06-03,Harvard,1992-06-16,4,NaN,NaN,4500000.0
6,J.T. Gray,NaN,NaN,NaN,NaN,NaN,Q,NaN,NaN,NaN,...,13.0,0.0,202.0,2000-06-01,Mississippi St.,1996-01-18,2,NaN,NaN,750000.0
7,Justin Hardee,NaN,NaN,NaN,NaN,O,NaN,NaN,IR,IR,...,7.0,0.0,200.0,2020-06-01,Illinois,1994-02-07,3,NaN,NaN,1135000.0
8,Deonte Harris,NaN,NaN,NaN,NaN,O,NaN,NaN,NaN,NaN,...,9.0,2.0,170.0,2020-05-06,Assumption,1997-12-04,1,NaN,NaN,675000.0
9,Trey Hendrickson,NaN,NaN,Q,NaN,NaN,NaN,NaN,NaN,NaN,...,13.0,13.0,270.0,2020-06-04,Florida Atlantic,1994-12-05,3,NaN,New Orleans Saints / 3rd / 103rd pick / 2017,825000.0
10,Josh Hill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,7.0,250.0,2020-06-05,Idaho St.,1990-05-21,7,NaN,NaN,1785000.0
11,Janoris Jenkins,NaN,NaN,NaN,O,O,NaN,NaN,NaN,NaN,...,10.0,10.0,190.0,2020-05-10,"North Alabama,Florida",1988-10-29,8,NaN,St. Louis Rams / 2nd / 39th pick / 2012,1050000.0
12,Derrick Kelly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.0,0.0,320.0,2020-06-05,Florida St.,1995-08-23,Rook,NaN,NaN,610000.0
13,Marshon Lattimore,NaN,NaN,NaN,O,Q,NaN,NaN,NaN,NaN,...,11.0,11.0,192.0,2000-06-01,Ohio St.,1996-05-20,3,NaN,New Orleans Saints / 1st / 11th pick / 2017,2559486.0
14,Ty Montgomery,NaN,NaN,IR,IR,IR,IR,IR,IR,NaN,...,4.0,0.0,216.0,2000-06-01,Stanford,1993-01-22,5,NaN,Green Bay Packers / 3rd / 94th pick / 2015,910000.0
15,David Onyemata,NaN,NaN,Q,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,12.0,300.0,2020-06-04,Manitoba,1992-11-13,4,NaN,New Orleans Saints / 4th / 120th pick / 2016,1000000.0
16,Andrus Peat,NaN,NaN,NaN,O,Q,NaN,NaN,NaN,NaN,...,11.0,11.0,316.0,2020-06-07,Stanford,1993-11-04,5,NaN,New Orleans Saints / 1st / 13th pick / 2015,1000000.0
17,Sheldon Rankins,NaN,NaN,NaN,NaN,Q,NaN,NaN,IR,IR,...,9.0,1.0,305.0,2020-06-02,Louisville,1994-04-02,4,NaN,New Orleans Saints / 1st / 12th pick / 2016,1690000.0
18,Cesar Ruiz,O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,7.0,307.0,2020-06-03,Michigan,1999-06-14,Rook,NaN,New Orleans Saints / 1st / 24th pick / 2020,610000.0
19,Emmanuel Sanders,NaN,NaN,NaN,NaN,NaN,C19,C19,C19,NaN,...,11.0,2.0,180.0,2020-05-11,SMU,1987-03-17,10,NaN,Pittsburgh Steelers / 3rd / 82nd pick / 2010,2000000.0
20,Michael Thomas,NaN,O,O,O,Q,O,O,Q,NaN,...,7.0,5.0,212.0,2020-06-03,Ohio St.,1993-03-03,4,NaN,New Orleans Saints / 2nd / 47th pick / 2016,1000000.0
21,Dwayne Washington,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q,...,9.0,0.0,223.0,2020-06-01,Washington,1994-04-24,4,NaN,Detroit Lions / 7th / 236th pick / 2016,910000.0
22,P.J. Williams,Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.0,1.0,196.0,2000-06-01,Florida St.,1993-06-01,4,NaN,New Orleans Saints / 3rd / 78th pick / 2015,1870000.0